<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Masuk ke Twitter</name>
   <tag></tag>
   <elementGuidId>98bb7822-21fd-42e1-8406-0189973dbd89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='modal-header']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#modal-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5f893166-2955-4dc1-b247-b8517d42afd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>3617ca31-3b09-4636-bee0-912a67c38590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fddbdf68-02d1-4d2f-aa43-abed1b2fd34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>3229b1ae-695d-4c56-957c-1c3d0cd76062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-18jsvk2 r-37j5jr r-1yjpyg1 r-b88u0q r-ueyrd6 r-bcqeeo r-qvutc0</value>
      <webElementGuid>e5cac374-1591-4bfe-b1fb-c2bdb034d6e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>modal-header</value>
      <webElementGuid>aaa1873d-c468-41e0-b07f-62c7e624f6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ocfSettingsListPrimaryText</value>
      <webElementGuid>63faf284-050b-42ea-9aa0-4bba08489ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk ke Twitter</value>
      <webElementGuid>8f5585aa-84f0-4bc1-9360-9b77fd2475a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-header&quot;)</value>
      <webElementGuid>5109cb59-b96b-43a1-9691-36e455bcd8f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='modal-header']</value>
      <webElementGuid>581328b7-9170-41a5-9459-850f49a779c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='layers']/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div/div/div/div/div/h1</value>
      <webElementGuid>e6a18474-c328-4d7f-a353-746b7151272b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk dengan Apple'])[1]/preceding::h1[1]</value>
      <webElementGuid>3664aeef-65d0-452a-871e-8aba775abb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>355b6223-e970-4bee-bf66-302f4f05af24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'modal-header' and (text() = 'Masuk ke Twitter' or . = 'Masuk ke Twitter')]</value>
      <webElementGuid>8d3437f2-3b4a-4cbb-b399-6b3a4e13758c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
